### ISSUE TITLE
Broken TOML is generated 

### ISSUE THREAD

**Issue by asm0dey** [mgree/ffs#67]
Consider the following TOML:

```toml
[a]
array = [ "a", 2, { x = "y", z = 3 } ]
key1 = "value1"
key2 = "value2"
```

It passes validation at https://www.toml-lint.com even tho it's slightly unconventional.

When I do the following

```shell
❯ ffs -i x.toml&
[1] 469278
❯ tree x
x
└── a
    ├── array
    │   ├── 0
    │   ├── 1
    │   └── 2
    │       ├── x
    │       └── z
    ├── key1
    └── key2

4 directories, 6 files
```
it seems valid.

All the data is valid too:
```shell
❯ cat x/a/array/0
a
❯ cat x/a/array/1
2
❯ cat x/a/array/2/x
y
❯ cat x/a/array/2/z
3
❯ cat x/a/key1
value1
❯ cat x/a/key2
value2
```

However when I unmount it, it's completely broken:

```shell
❯ umount x
[1]  + 469278 done       ffs -i x.toml
❯ cat x.toml
[a]
key1 = "value1"
key2 = "value2"
array = ["a", 2
[[a.array]]
x = "y"
z = 3
]
```

**Comment by asm0dey** [comment]
Compiled version is the only one I tried, let me try to update the version :)

**Comment by asm0dey** [comment]
Yup, updating fixes it!

**Comment by mgree** [comment]
#68 is set to merge when CI says it's good, which should generate a usable executable. Thanks for the report!

**Comment by asm0dey** [comment]
Will there be a new release published?
